### ISSUE TITLE
NEED HELP!

### ISSUE THREAD

**Issue by XiangtaiKong** [NSSSJSS/MHGCN#1]
I git clone the codes and constructed the required environment. But after running the Link_prediction of IMDB dataset, the answers are only ROC 0.56, F1 0.56, PR 0.57, whether there is anything wrong I did or the data is insufficient?

**Comment by NSSSJSS** [comment]
> I git clone the codes and constructed the required environment. But after running the Link_prediction of IMDB dataset, the answers are only ROC 0.56, F1 0.56, PR 0.57, whether there is anything wrong I did or the data is insufficient?
We made some mistakes when uploading the dataset, and the new dataset has been uploaded again.

**Comment by JackChen0910** [comment]
> I git clone the codes and constructed the required environment. But after running the Link_prediction of IMDB dataset, the answers are only ROC 0.56, F1 0.56, PR 0.57, whether there is anything wrong I did or the data is insufficient?
请问一下你用新上传的数据集复现了吗到论文中的准确度了吗？

**Comment by XiangtaiKong** [comment]
并没有，虽然相较于之前的数据集有所上升，但离文章中的结果0.96还有不少差距





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NSSSJSS/MHGCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月22日(星期四) 下午2:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NSSSJSS/MHGCN] NEED HELP! (Issue #1)发送





  
I git clone the codes and constructed the required environment. But after running the Link_prediction of IMDB dataset, the answers are only ROC 0.56, F1 0.56, PR 0.57, whether there is anything wrong I did or the data is insufficient?
 请问一下你用新上传的数据集复现了吗到论文中的准确度了吗？

**Comment by ivam-he** [comment]
Did the author upload a new dataset? Where is it?

**Comment by XiangtaiKong** [comment]
The one you can see is new




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NSSSJSS/MHGCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月30日(星期五) 上午8:39
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [NSSSJSS/MHGCN] NEED HELP! (Issue #1)





 
Did the author upload a new dataset? Where is it?
