### ISSUE TITLE
CPU or GPU? 

### ISSUE THREAD

**Issue by FinchNie** [NSSSJSS/MHGCN#12]
Were the experiments conducted using a CPU or a GPU? I noticed that the code repository specifies the device as CPU, and the paper reports the use of a GPU with 8GB of memory. However, when I attempted to run the provided DBLP dataset directly from the repository, it resulted in an Out of Memory (OOM) error. So, should the model be run using a CPU?

**Comment by ywl2003** [comment]
I have the same problem and I think it can be solved by converting it to a sparse matrix.
