### ISSUE TITLE
Can you provide me with Alibaba Dataset？

### ISSUE THREAD

**Issue by liamyx** [NSSSJSS/MHGCN#2]
Dataset Alibaba https://tianchi.aliyun.com/competition/entrance/231719/information/）can't be downloaded?

**Comment by liamyx** [comment]
I will be so grateful if you can send the Alibaba dataset  to my email address makeit_lyx@163.com

**Comment by GorgeousMe** [comment]
Hello , Could you send me the Alibaba dataset, My email address tangqihaokk@gmail.com , Thanks a lot !

**Comment by trytodoit227** [comment]
Hello , Could you share the Alibaba dataset, My email address is  m18811368219@163.com , Thanks a lot !

**Comment by FuChF** [comment]
We have sent the dataset to friends who need it, please check it, we hope it can help you.

**Comment by Rumial** [comment]
Hello, I'd like to ask whether you could share the Alibaba dataset and the Amazon dataset which are used as experimental data in your paper. My email is rumial@foxmail.com, Thanks very much and I will be really grateful.

**Comment by liu-yang-maker** [comment]
Hello , Could you share the Amazon dataset, my email is liuyang2020@amss.ac.cn. I really need it! Thanks very much and I will be really grateful.

**Comment by Rumial** [comment]
发自我的iPhone


------------------ Original ------------------
From: liu-yang-maker ***@***.***&gt;
Date: Tue,Oct 18,2022 11:12 PM
To: NSSSJSS/MHGCN ***@***.***&gt;
Cc: Rumial ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [NSSSJSS/MHGCN] Can you provide me with Alibaba Dataset？ (Issue #2)





 
Hello , Could you share the Amazon dataset, my email is ***@***.*** I really need it! Thanks very much and I will be really grateful.

**Comment by GorgeousMe** [comment]
你好，可以提供一下Alibaba的数据集吗？我的邮箱：1464692971@qq.com，非常感激不尽！

**Comment by NSSSJSS** [comment]
Alibaba数据集已经上传github链接了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月31日(星期一) 下午3:00
收件人: "NSSSJSS/MHGCN";
抄送: "Subscribed";
主题: Re: [NSSSJSS/MHGCN] Can you provide me with Alibaba Dataset？ (Issue #2)





 
***@***.***，非常感激不尽！
 
&mdash;

**Comment by farukakgul** [comment]
Hi @FuChF I have been struggling to find the Amazon and Alibaba datasets, as well. Can you forward it to omerfarukakgul1999@gmail.com too? Thank you.

**Comment by OnlineWaAndRe** [comment]
这个是不是简单的一个实现，并没有给出全部的代码啊

**Comment by OnlineWaAndRe** [comment]
能对阿里巴巴数据集进行详细的说明吗，IUI_buy,以及full_feature数据的说明。我看里面item_num.shape = 4025,  user_num = 17293,  full_feature = 21318 * 19,  确实不太懂 这个19是什么意思， 还有就是IUI_buy大小也是4025 * 4025 , 不太明白意思。看了您的代码 好像是个大致的框架，也没看出头脑出来，您能解答一下吗？ 万分感谢

**Comment by OnlineWaAndRe** [comment]
@farukakgul @Rumial @FuChF @GorgeousMe

**Comment by hauldhut** [comment]
Hi authors,
I am really appreciate your work.
I am now struggling with downloading the datasets you mentioned in the repo, since I am not located in China.
Please send the download links to those datasets for me to hauldhut@gmail.com

Thanks and Best regards,
