### ISSUE TITLE
The results of baselines on DBLP 

### ISSUE THREAD

**Issue by ivam-he** [NSSSJSS/MHGCN#3]
Hi,
Why the results of baselines(e.g., HAN, GTN) on DBLP is too low (compared with the results reported in their papers)?

**Comment by ivam-he** [comment]
> Please read the details carefully. The DBLP dataset used in our work is different from the one you listed in terms of node number and feature information.

Thank you for your prompt response; it was my fault. I checked the details in the paper again, and there is no mention of processing for the original DBLP dataset (https://dblp.uni-trier.de). Now, you claim that you have processing for the original DBLP. Could you explain why you do this? What relations are included in the new DBLP dataset, and how are the 4635-dimensional features obtained? I am curious about the reasons.

**Comment by EulerKMS** [comment]
I have the same question, why the reprocessing of DBLP?

**Comment by NSSSJSS** [comment]
We did not reprocess the DBLP dataset. We used the DBLP dataset used in WWW '20 Paper MAGNN.

**Comment by ivam-he** [comment]
> We did not reprocess the DBLP dataset. We used the DBLP dataset used in WWW '20 Paper MAGNN.

I see. However, why do the results of HAN and MAGNN reported in your paper differ dramatically from those in the MAGNN paper, although using the same dataset and maintaining baseline hyperparameter settings?

**Comment by NSSSJSS** [comment]
Yes, it is recommended that you complete the relevant experiments independently.
