### ISSUE TITLE
About the Compressed Datasets

### ISSUE THREAD

**Issue by ivam-he** [NSSSJSS/MHGCN#4]
Is it possible to provide more compressed datasets (e.g., AMiner, Alibaba, IMDB) or their preprocessing codes? I can't reproduce the results of MHGCN in Table 3 except for DBLP.

**Comment by NSSSJSS** [comment]
We will upload Alibaba dataset in the next few days.

**Comment by ivam-he** [comment]
> We will upload Alibaba dataset in the next few days.

Thank you for your prompt reply; I would be very grateful if you could provide the Alibaba dataset. How about AMiner and IMDB? A standard compressed code or a processed ".mat" file would be good. Forgive me for asking too many questions. I like the simplicity of EMGCN and believe it can achieve an average improvement of more than 10%, which is significant, so I want to reproduce these experimental results.
