### ISSUE TITLE
Where is the Aminer dataset?

### ISSUE THREAD

**Issue by EulerKMS** [NSSSJSS/MHGCN#5]
The link "https://github.com/librahu/" for the Aminer dataset links to a GitHub account; where can I obtain the dataset? It's not a new dataset you've proposed; you must cite its source instead of just providing an empty link. It's not good!

**Comment by NSSSJSS** [comment]
https://github.com/librahu/HIN-Datasets-for-Recommendation-and-Network-Embedding/tree/master/Aminer
