### ISSUE TITLE
I would like to point out a simple error in the readme

### ISSUE THREAD

**Issue by huangyueshiqi** [NSSSJSS/MHGCN#6]
In the process of my reproduction, the usage in the readme about running the Node_Classfication.py code is wrong.Should be "python Node_Classfication.py", not "python python Node_Classification.py". You guys did a great job and this is a great article. Sorry, but I may be a little OCD, I noticed that you guys updated the github repo but didn't change this little bug.

**Comment by NSSSJSS** [comment]
Thank you for your correction. We have made changes.
