### ISSUE TITLE
Why some edges in the test data couldn't be found in the original dataset?

### ISSUE THREAD

**Issue by Rumial** [NSSSJSS/MHGCN#7]
I downloaded the IMDB dataset and there were three txt files called test, train and valid. I compared the test data with the original dataset (given by imdb_1_10.mat) and I found out that some links in the test data which are regared as positive links don't exist in the original dataset at all.
Do you have any ideas what happend?

**Comment by NSSSJSS** [comment]
We checked the data set and did not find what you said.

**Comment by NSSSJSS** [comment]
IMDB has two types of edges, so it has two adjacency matrices. I don't know if you don't have a good correspondence.

**Comment by Rumial** [comment]
I did consider those two adjacency matrices. I'm wondering whether the test data I downloaded went wrong since I couldn't find it   
 in the data catalog right now. About IMDB, there is only imdb.mat file following the links given by Tips. Where can I get those train, test, and valid data used for link prediction in IMDB? Thank you very much!
