### ISSUE TITLE
dataset IMDB lack several files

### ISSUE THREAD

**Issue by porvinci** [NSSSJSS/MHGCN#9]
Hello, recently i am reading your article, your work is excellent and i want to reproduce the link prediction on IMDB dataset.
I have downloaded the imdb_1_10.mat file, but when i run it, it reminded me that there are lack of these files: 
data/IMDB/train.txt, data/IMDB/valid.txt, data/IMDB/test.txt
Can you upload these files? Thanks in advance. Wish you good luck.

**Comment by hussien** [comment]
Hi @porvinci , can you please provide the link for the IMDB dataset, if you can mail it to : hussein.abdallah@mail.concordia.ca I will be really thankful.

**Comment by porvinci** [comment]
> Hi @porvinci , can you please provide the link for the IMDB dataset, if you can mail it to : [hussein.abdallah@mail.concordia.ca](mailto:hussein.abdallah@mail.concordia.ca) I will be really thankful.

you can find the link from here https://github.com/NSSSJSS/MHGCN/blob/master/data/IMDB/Tips

**Comment by hussien** [comment]
> > Hi @porvinci , can you please provide the link for the IMDB dataset, if you can mail it to : [hussein.abdallah@mail.concordia.ca](mailto:hussein.abdallah@mail.concordia.ca) I will be really thankful.
> 
> you can find the link here https://github.com/NSSSJSS/MHGCN/blob/master/data/IMDB/Tips

Hi @porvinci, i can't download from the hosting website it keeps refreshing the page without being able to download. can you please provide steps on how to download that .mat files?
